// Generated by CoffeeScript 1.10.0
(function() {
  var ValueCreator, assertType, isType, ref;

  ref = require("type-utils"), isType = ref.isType, assertType = ref.assertType;

  ValueCreator = require("./ValueCreator");

  module.exports = ValueCreator("BoundMethodCreator", {
    init: function(keys) {
      if (!isType(keys, Array)) {
        return;
      }
      return function() {
        var boundMethod, boundMethods, i, key, len, method;
        boundMethods = {};
        for (i = 0, len = keys.length; i < len; i++) {
          key = keys[i];
          method = this[key];
          assertType(method, Function, {
            key: this.constructor.name + "." + key,
            instance: this
          });
          boundMethod = method.bind(this);
          boundMethod.toString = function() {
            return method.toString();
          };
          boundMethods[key] = {
            value: boundMethod,
            enumerable: key[0] !== "_"
          };
        }
        return boundMethods;
      };
    }
  });

}).call(this);
