// Generated by CoffeeScript 1.10.0
(function() {
  var ValueCreator, assertType, combine, isType, ref, sync;

  ref = require("type-utils"), isType = ref.isType, assertType = ref.assertType;

  sync = require("io").sync;

  combine = require("combine");

  ValueCreator = require("./ValueCreator");

  module.exports = ValueCreator("CustomValueCreator", {
    init: function(reusedConfigs) {
      var config, key;
      if (!isType(reusedConfigs, Object)) {
        return;
      }
      for (key in reusedConfigs) {
        config = reusedConfigs[key];
        assertType(config, Object);
        config.enumerable = key[0] !== "_";
        if (config.configurable == null) {
          config.configurable = false;
        }
      }
      return function() {
        return combine({}, reusedConfigs);
      };
    }
  });

}).call(this);
