// Generated by CoffeeScript 1.10.0
(function() {
  var ValueCreator, sync;

  sync = require("io").sync;

  ValueCreator = require("./ValueCreator");

  module.exports = ValueCreator("FrozenValueCreator", {
    transform: function(values) {
      return sync.map(values, function(value, key) {
        return {
          value: value,
          frozen: true,
          enumerable: key[0] !== "_"
        };
      });
    }
  });

}).call(this);
