// Generated by CoffeeScript 1.10.0
var ValueCreator, sync;

sync = require("sync");

ValueCreator = require("./ValueCreator");

module.exports = ValueCreator("FrozenValueCreator", {
  transform: function(values) {
    return sync.map(values, function(value, key) {
      return {
        value: value,
        frozen: true
      };
    });
  }
});
