// Generated by CoffeeScript 1.10.0
var ValueCreator, sync;

sync = require("sync");

ValueCreator = require("./ValueCreator");

module.exports = ValueCreator("WritableValueCreator", {
  transform: function(values) {
    return sync.map(values, function(value) {
      return {
        value: value
      };
    });
  }
});
